### ISSUE TITLE
DOI allocation

### ISSUE THREAD

**Issue by vturpin** [OceanGlidersCommunity/OG-format-user-manual#20]
suggest a rule like :

- DOI can be minted at any level (PI, Reference Data Center, Data Assembly Center, Global Data Assembly Center) following the internal policy of data curation.
- DOI can be minted for a single glider mission or multiple glider missions (i.e. project, reference lines).
- When a DOI is minted for a data set, the DOI must remain unchanged if there is no valuable modification. If valuable information is aggregated/added or a new product produced, a new DOI shall be created and the new DOI MUST link to the original DOI to acknowledge as the source
- GDACs will create an evolving global data set with a DOI referring to all existing DOIs.

**Comment by justinbuck** [comment]
Mark and Justin (BODC) had a look at this and agree that the DOI if included in OG files needs to be preserved. When the data citation infrastructure enables the graphed DOIs to be maintained and queried via services like data common then this decisions can be reviewed, until then the most effective way of preserving the integrity of the source citation is to preserve the DOI added by the DAC in the OG file.

**Comment by soerenthomsen** [comment]
@isgiddy discussion might interest you too.

**Comment by vturpin** [comment]
I've made a pull request in that sense : #54 . Issue will be close if pull request is accepted.

**Comment by castelao** [comment]
@justinbuck , thanks for sharing that document. Nice work. Would you like to suggest incorporating anything from that into OG-1.0 recommendations? I still think that the recommended for higher levels, such as projects and campaigns should be DOIs, and transition to alternative solutions such as PIDs once reaching sensors and dataset versions.

About your previous comment, it is important to clarify the scenario where the DAC's DOI is not the first one defined. For instance, once Spray data reaches the DAC it already has a DOI which must not be ignored, as described in #54.

About the schema proposed in the document, would it be easier to recommend the inverse relationship of HasPart (I think the inverse is IsPartOf)? Otherwise, any new product, let's say a new dataset version, would require updates all the way up. But with the inverse relationship, only the new product needs to know and define who is above it.

**Comment by glidermann** [comment]
I think this is adequately addressed in #54 which has been merged. We should try to include the contribution of @justinbuck above in the publication of this manual to further illustrate the power of this policy.
