### ISSUE TITLE
New OG1 vocabulary term - Downwelling irradiance at 655nm 

### ISSUE THREAD

**Issue by danibodc** [OceanGlidersCommunity/OG-format-user-manual#257]
We have received a request for a new OG1 term for downwelling irradiance  at 655 nm, measured from a Satlantic OCR504 downwelling irradiance sensor. Measures irradiance intensity at 4 factory set wavelengths (443, 490, 555 & 655 nm) in μWcm-2nm-1.

**Proposed identifier:** ED655
**Proposed preferred label:** Downwelling irradiance at 655 nanometers
**Proposed alternative label:** DOWN_IRRADIANCE655
**Proposed definition:** The vertical component of light at 655 nm wavelength travelling downwards.

This would be mapped to P06 units term UWNM- Watts per square metre per nanometre (https://vocab.nerc.ac.uk/collection/P06/current/UWNM/) to maintain consistency with existing unit mappings for similar irradiance terms in OG1.

**Comment by fmargirier** [comment]
fine by me, is also coherent with other variable names

**Comment by clayton33** [comment]
makes sense, approval from me.

**Comment by emmerbodc** [comment]
@danibodc can you please create this new OG1 term please

**Comment by callumrollo** [comment]
Hi all, I'm converting out glider data to OG1 atm and we also have sevaral OCR-504 sensors. Ours are made by Seabird though, not Satlantic. I've gone on a bit of a dive through the vocab server to find the root of this. Satlantic merged with Seabird in 2011 (their website even redirects to seabird.com), so I think all sensors built after that would more accurately be Seabird OCR-504, rather than Satlantic OCR-504.

I'm not sure how to resolve this with controlled vocabs, so I've posted an Issue in the NVS github to discuss https://github.com/nvs-vocabs/L22/issues/273

**Comment by fmargirier** [comment]
Hi Callum, there might be a similar issue with ECO puck Seabird sensors (FLBBCD etc) which were previously WET-Labs. I'll investigate further.

**Comment by emmerbodc** [comment]
@callumrollo  that is the best place to raise this. We had to the same with WetLabs instruments too and changed them all recently for this.

**Comment by danibodc** [comment]
The new term has now been loaded to OG1:

ED655	Downwelling irradiance at 655 nanometers

Queued for overnight publication - URI will be live on the NVS from tomorrow morning:
https://vocab.nerc.ac.uk/collection/OG1/current/ED655/
