### ISSUE TITLE
Specification of the version of NetCDF in the OceanGliders format

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#29]
Hi,
The format specification does not currently specify which version of NetCDF we are using. From memory, discussions coverage on NetCDF 4 but I am not sure which version (classic or non-classic).
@castelao  @vturpin  which was used for the example file and do we have the minutes for the decision please?
Once confirmed we need to add the version to the format specification.
Justin

**Comment by castelao** [comment]
@justinbuck , that's a good point! The example that I made was with full NetCDF4.

I'm pretty sure that the decision was on using the full (non-classic), but only @vturpin can confirm it with the notes from that meeting.

**Comment by justinbuck** [comment]
Thank you @castelao , We will use  full (non-classic) initially too until confirmed

**Comment by vturpin** [comment]
This NETCDF4 should be stated in the format. I've made a pull request #51 in that sense. When merged, we can close this issue.

**Comment by castelao** [comment]
@justinbuck , I couldn't find on ACDD-1.3 where it defines the NetCDF4 version as a highly required metadata. I think it is worth confirming this to make a decision here. Also, I don't think CF explicitly imposes a version, but some features do require a newer version.

I used NetCDF-4 because we made a few decisions on the way that made NetCDF-3 incompatible for us. We require some advances from version 4.

I don't think we need to lock on version 4 of NetCDF. Not because the version is embedded in the file, since we are not proposing a decoder. But we shouldn't care which version of NetCDF is used as long as it satisfies our data model. For instance, NetCDF-3 doesn't allow String. Thinking about the future, we shouldn't restrict ourselves to NetCDF-4, but be ready for progress, as long as it is back compatible.

I suggest mentioning in the document that it was used NetCDF-4 to save time for new users, but I don't see at this point the need to record in the file or lock OG-1.0 with NetCDF-4.

**Comment by justinbuck** [comment]
@castelao https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3 is will be under the netcdf conventions handbook link in this page but I am getting a 404 at the moment.
https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3

**Comment by castelao** [comment]
@justinbuck maybe it was a momentary problem? That link is working for me now.

**Comment by castelao** [comment]
Responding #50 here to avoid duplicates and the discussion consistent.

@justinbuck , NetCDF-3 is past, no reason for that concern. Anyone trying that will find out that it is technically not possible to satisfy OG-1.0 with NetCDF-3. Don't worry about it.

My concern is in the other direction. Do we want to limit ourselves to the possibility in the future of using anything newer than our current NetCDF-4? I think we should focus on the data model and allow freedom for anything that satisfies that.

My understanding is that we have two points in the discussion here:
- Should we define the OG-1.0 as strictly NetCDF-4?
- Should we explicitly define the NetCDF-4 with some attribute (a global one)?

My opinion: We don't need to restrict to NetCDF-4, thus we don't need to inform the type as an attribute. That said, we should note in the manual that version 3 doesn't satisfy the requirements to save time for future developers.

**Comment by gkrahmann** [comment]
I agree with Gui.
4 is fine (for the moment) and an attribute would be 100% meaningless, since, if you can read the attribute you already
know that it is 4...
It should however be properly mentioned in the manual.

**Comment by vturpin** [comment]
I agree too

**Comment by vturpin** [comment]
I've edit the PR #50  removing the restriction to NetCDF-4 and notifying that NetCDF-3 does not fullfuil OG1.0 needs.
