### ISSUE TITLE
OG1 file naming convention

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/OG-format-user-manual#31]
We found an omission the current format specification, there is no description on how files, should be named. Initially should we just follow the EGO convention?
https://archimer.ifremer.fr/doc/00239/34980/88416.pdf section 5.1

**Comment by castelao** [comment]
@justinbuck , I remember this discussion happening before, and I believe that the recommendation was:

`<platform_code>-<start_time>_<data_mode>.nc`

which is `<trajectory>_<data_mode>.nc`

for example:

`sp065-20210616T1430_R.nc`

There is that other discussion about using "-" or "_". I don't think that one got a resolution yet, did it?

Also, since we have all metadata inside the file, we might add in the document as a recommendation only, and allow freedom if someone has good reasons for another naming convention... It would be nice if everyone followed the same filename convention but I think that we shouldn't rely on information from the filename but only from the content. 

@vturpin , do you remember when was that discussed? Would you have notes from that meeting?

Whatever is the recommendation, I agree with @justinbuck that it is a good thing to add to the document. My suggestion is to be a recommendation instead of a requirement.

**Comment by justinbuck** [comment]
@castelao 
3.15Reference table 19: data modes
The values for the global attribute “data_mode” is defined as follows:
Value Meaning
R
Real-time data. Data coming from the (typically remote) platform through a communication channel without physical
access to the instruments, disassembly or recovery of the platform. Example: for a glider with a radio
communication, this would be data obtained through the radio.
P
Provisional data. Data obtained after the instruments or the platform have been recovered or serviced. Example: for
instruments on a glider, this would be data downloaded directly from the instruments after the glider has been
recovered on a ship.
A Rea-time adjusted data. Real-time or provisional data that have been adjusted by real-time automatic procedures.
D
Delayed-mode data. Data published after all calibrations and quality control procedures have been applied on the
internally recorded or best available original data. This is the best possible version of processed data.
M Mixed. This value indicates that the file contains data in more than one of the above states.

**Comment by vturpin** [comment]
I have just made a pull request in that sense.

**Comment by glidermann** [comment]
#51 is agreed upon...
